=== poreid/poreid/poreid/src/main/resources/org/poreid/config/schema/poreid.config.xsd
<?xml version="1.0"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns="http://config.por.eid" targetNamespace="http://config.por.eid">
    <xs:element name="configuration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="poreid-supported-smartcards" type="SupportedSmartCardsModeller" minOccurs="0"/>
                <xs:element name="smartcard-pinpad-readers" type="SmartCardPinPadReadersModeller" minOccurs="0"/>
                <xs:element name="default-locale" type="locale"/>
                <xs:element name="allow-external-pin-caching" type="external-pin-cache"/>
                <xs:element name="timed-interaction" type="use-timed-interaction"/>
                <xs:element name="cache-threshold" type="xs:nonNegativeInteger" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="SupportedSmartCardsModeller">
        <xs:sequence>
            <xs:element name="smartcard" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="atr" type="xs:string"/>
                        <xs:element name="properties" type="SmartCard"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SmartCard">
        <xs:sequence>
            <xs:element name="implementing-class" type="xs:string"/>
            <xs:element name="cache-enabled" type="xs:boolean"/>
            <xs:element name="validity" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType> 
    <xs:complexType name="SmartCardPinPadReadersModeller">
        <xs:sequence>
             <xs:element name="aliases" type="AliasesOfModeller"/>
             <xs:element name="smartcard-readers" type="SmartCardReaderModeller"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AliasesOfModeller">
        <xs:sequence>
             <xs:element name="alias-of" type="AliasesModeller" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AliasesModeller">
        <xs:sequence>
             <xs:element name="alias" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="unique-id" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="SmartCardReaderModeller">
       <xs:sequence>
            <xs:element name="smartcard-reader" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="unique-id" type="xs:string"/>
                        <xs:element name="properties" type="SmartCardReader"/>
                    </xs:sequence>                
                </xs:complexType>
            </xs:element>
       </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SmartCardReader">
        <xs:sequence>
            <xs:element name="implementing-class" type="xs:string"/>
            <xs:element name="supported-oses" type="OsSupportModeller" maxOccurs="1" minOccurs="0"/>
            <xs:element name="supported-smartcards" type="SmartCardSupportModeller" maxOccurs="1" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OsSupportModeller">
        <xs:sequence>
            <xs:element name="os" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="os-name" type="os-type"/>
                        <xs:element name="supports" type="OsSupport"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OsSupport">
        <xs:sequence>
            <xs:element name="verify" type="xs:boolean"/>
            <xs:element name="modify" type="xs:boolean"/>
            <xs:element name="inject" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SmartCardSupportModeller">
        <xs:sequence>
            <xs:element name="smartcard" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="implementing-class" type="xs:string"/>
                        <xs:element name="properties" type="SmartCardSupport"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SmartCardSupport">
        <xs:sequence>
            <xs:element name="verify" type="xs:boolean"/>
            <xs:element name="modify" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="locale">
        <xs:attribute name="language" type="xs:string" use="required"/>
        <xs:attribute name="country" type="xs:string" use="optional" default=""/>
    </xs:complexType>
    <xs:simpleType name="os-type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="windows"/>
            <xs:enumeration value="linux"/>
            <xs:enumeration value="mac"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="external-pin-cache">
        <xs:attribute name="status" type="xs:boolean" default="false"/>
    </xs:complexType>
    <xs:complexType name="use-timed-interaction">
        <xs:sequence>
            <xs:element name="enabled" type="xs:boolean" default="false"/>
            <xs:element name="period" type="xs:positiveInteger" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== poreid/poreid/poreid/src/main/resources/org/poreid/config/xml/poreid.config.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://config.por.eid" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://config.por.eid poreid.config.xsd">
    <poreid-supported-smartcards>
        <smartcard>
            <atr>3BFF9600008131FE4380318065B085040120120FFF829000D0</atr>
            <properties>
                <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>
        <smartcard>
            <atr>3BFF9600008131804380318065B0850300EF120FFF82900067</atr>
            <properties>
                <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>
        <smartcard>
            <atr>3B7D95000080318065B08311C0A98300</atr>
            <properties>
                <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>
        <smartcard>
            <atr>3B7D95000080318065B08311C0A983009000</atr>
            <properties>
                <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>
        <smartcard>
            <atr>3B7D95000080318065B0831100C88300</atr>
            <properties>
                <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>
        <smartcard>
            <atr>3B7D95000080318065B0831100C883009000</atr>
            <properties>
                <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>
        <smartcard>
            <atr>3B650000D000540131</atr>
            <properties>
                <implementing-class>org.poreid.cc.ias.IASCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard> 
        <smartcard>
            <atr>3B650000D000540132</atr>
            <properties>
                <implementing-class>org.poreid.cc.ias.IASCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>  
        <smartcard>
            <atr>3B959540FFD000540131</atr>
            <properties>
                <implementing-class>org.poreid.cc.ias.IASCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>  
        <smartcard>
            <atr>3B959540FFD000540132</atr>
            <properties>
                <implementing-class>org.poreid.cc.ias.IASCard</implementing-class>
                <cache-enabled>true</cache-enabled>
            </properties>
        </smartcard>
    </poreid-supported-smartcards>
    <smartcard-pinpad-readers>
        <aliases>
            <alias-of unique-id="IDBridgeCT700">
                <alias>Gemalto GemPC Pinpad USB Smart Card Read</alias>
                <alias>Gemalto USB GemPCPinpad SmartCard Reader</alias>
                <alias>Gemplus GemPC Pinpad</alias>
                <alias>Gemalto Ezio Shield</alias>                
            </alias-of>
            <alias-of unique-id="ACR83 PINeasy">
                <alias>ACS ACR83U</alias>
            </alias-of>
            <alias-of unique-id="XIRING MyLeo">
                <alias>XIRING MyLeo (123456789)</alias>
                <alias>XIRING USB Smart Card Reader</alias>
            </alias-of>
            <alias-of unique-id="generic reader">
                <alias>generic reader</alias>
            </alias-of>
        </aliases>
        <smartcard-readers>
            <smartcard-reader>
                <unique-id>ACR83 PINeasy</unique-id>
                <properties>
                    <implementing-class>org.poreid.pinpad.AcsACR83u</implementing-class>
                    <supported-oses>
                        <os>
                            <os-name>windows</os-name>
                            <supports>
                                <verify>true</verify>
                                <modify>true</modify>
                                <inject>true</inject>
                            </supports>
                        </os>
                        <os>
                            <os-name>linux</os-name>
                            <supports>
                                <verify>true</verify>
                                <modify>true</modify>
                                <inject>true</inject>
                            </supports>
                        </os>
                        <os>
                            <os-name>mac</os-name>
                            <supports>
                                <verify>false</verify>
                                <modify>false</modify>
                                <inject>true</inject>
                            </supports>
                        </os>
                    </supported-oses>
                    <supported-smartcards>
                        <smartcard>
                            <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
                            <properties>
                                <verify>true</verify>
                                <modify>false</modify>
                            </properties>
                        </smartcard>
                        <smartcard>
                            <implementing-class>org.poreid.cc.ias.IASCard</implementing-class>
                            <properties>
                                <verify>true</verify>
                                <modify>false</modify>
                            </properties>
                        </smartcard>
                    </supported-smartcards>
                </properties>
            </smartcard-reader>
            <smartcard-reader>
                <unique-id>IDBridgeCT700</unique-id>
                <properties>
                    <implementing-class>org.poreid.pinpad.GemaltoIDBridgeCT700</implementing-class>
                    <supported-oses>
                        <os>
                            <os-name>windows</os-name>
                            <supports>
                                <!-- estes senhores tÃªm um problema no driver em windows -->
                                <verify>true</verify>
                                <modify>true</modify>
                                <inject>true</inject>
                            </supports>
                        </os>
                        <os>
                            <os-name>linux</os-name>
                            <supports>
                                <verify>true</verify>
                                <modify>true</modify>
                                <inject>true</inject>
                            </supports>
                        </os>
                        <os>
                            <os-name>mac</os-name>
                            <supports>
                                <verify>true</verify>
                                <modify>true</modify>
                                <inject>true</inject>
                            </supports>
                        </os>
                    </supported-oses>
                    <supported-smartcards>
                        <smartcard>
                            <implementing-class>org.poreid.cc.gemsafe.GemsafeCard</implementing-class>
                            <properties>
                                <verify>true</verify>
                                <modify>true</modify>
                            </properties>
                        </smartcard>
                        <smartcard>
                            <implementing-class>org.poreid.cc.ias.IASCard</implementing-class>
                            <properties>
                                <verify>true</verify>
                                <modify>true</modify>
                            </properties>
                        </smartcard>
                    </supported-smartcards>
                </properties>
            </smartcard-reader>
            <smartcard-reader>
                <unique-id>XIRING MyLeo</unique-id>
                <properties>
                    <implementing-class>org.poreid.pinpad.XiringMyleo</implementing-class>
                    <supported-oses>
                        <os>
                            <os-name>windows</os-name>
                            <supports>
                                <verify>true</verify>
                                <modify>true</modify>
                                <inject>false</inject>
                            </supports>
                        </os>
                        <os>
                            <os-name>linux</os-name>
                            <supports>
                                <verify>true</verify>
                                <modify>true</modify>
                                <inject>true</inject>
                            </supports>
                        </os>
                        <os>
                            <os-name>mac</os-name>
                            <supports>
                                <verify>false</verify>
                                <modify>false</modify>
                                <inject>false</inject>
                            </supports>
                        </os>
                    </supported-oses>
                    <supported-smartcards>
                        <smartcard>
